// <auto-generated />
using BunAndFun.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BunAndFun.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318003526_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BunAndFun.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Cakes",
                            ImageUrl = "assets/cake1.jpg",
                            Name = "Double Chocolate Cake",
                            Price = 28.50m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Sandwiches",
                            ImageUrl = "assets/sand1.jpg",
                            Name = "Veggie Club Sandwich",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Pastries",
                            ImageUrl = "assets/past1.jpg",
                            Name = "Almond Croissant",
                            Price = 5.25m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
